export const SlotEvent = {
    ENTER_FRAME: "ENTER_FRAME",

    SPIN_CLICK: "SPIN_CLICK",
    STOP_CLICK: "STOP_CLICK",

    REELS_SPIN_STARTED: "REELS_SPIN_STARTED",
    REELS_STOPPED: "REELS_STOPPED",

    SERVER_SPIN_RESPONSE_RECEIVED: "SERVER_SPIN_RESPONSE_RECEIVED",
    SERVER_INIT_RESPONSE_RECEIVED: "SERVER_INIT_RESPONSE_RECEIVED",

    SLOT_STATE_CHANGED: "SLOT_STATE_CHANGED",

    NEW_REELS_TAPES_RECEIVED: "NEW_REELS_TAPES_RECEIVED"

};

export const KeyBoardEvent = {
    SPACE_DOWN: "KeyBoardEvent.SPACE_DOWN",
    SPACE_UP: "KeyBoardEvent.SPACE_UP",

};