export const LoaderEvent = {
  FILE_LOADING_STARTED: "FILE_LOADING_STARTED" ,
  FILE_LOADED: "FILE_LOADED" ,
  ALL_FILES_LOADED: "ALL_FILES_LOADED" ,
};

export const LoadingManagerEvent = {
  PRELOAD_ASSETS_LOADED:"PRELOAD_ASSETS_LOADED",
  MAIN_ASSETS_LOAD_PROGRESS:"MAIN_ASSETS_LOAD_PROGRESS",
  MAIN_ASSETS_LOADED:"MAIN_ASSETS_LOADED"
};